{
 "title": "Jobs",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "filters" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(requests_started_total, job_name)"
    }
   },
   {
    "name": "job_version",
    "label": "job_version",
    "query": {
     "query": "label_values(requests_started_total, job_version)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Job requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate of calls",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job_name,job_version)(irate(requests_started_total{job_name=~\"$job_name\",job_version=~\"$job_version\"}[$__rate_interval]) > 0)",
     "legendFormat": "{{job_name}} {{job_version}}"
    }
   ]
  },
  {
   "title": "Total calls (in the selected range)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (job_name,job_version,endpoint)(idelta(endpoint_requests_started_total{job_name=~\"$job_name\",job_version=~\"$job_version\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Internal Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(request_internal_errors_total{job_name=~\"$job_name\",job_version=~\"$job_version\"} or vector(0)) - sum(request_internal_errors_total{job_name=~\"$job_name\",job_version=~\"$job_version\"} offset 1m or vector(0))",
     "legendFormat": "{{job_name}} {{job_version}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Active requests (Unfinished)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (job_name,job_version)(requests_started_total{job_name=~\"$job_name\",job_version=~\"$job_version\"} - requests_done_total{job_name=~\"$job_name\",job_version=~\"$job_version\"})",
     "legendFormat": "{{job_name}} {{job_version}}"
    }
   ]
  },
  { "title": "Job response time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Response time histogram over time",
   "type": "heatmap",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(idelta(request_duration_bucket{job_name=~\"$job_name\",job_version=~\"$job_version\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response time histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (max_over_time(request_duration_bucket{job_name=~\"$job_name\",job_version=~\"$job_version\"}[$__range])) - \nsum by(le) (min_over_time(request_duration_bucket{job_name=~\"$job_name\",job_version=~\"$job_version\"}[$__range]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Average Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(request_duration_sum{job_name=~\"$job_name\",job_version=~\"$job_version\"}) by (job_name, job_version) / sum(request_duration_count{job_name=~\"$job_name\",job_version=~\"$job_version\"}) by (job_name, job_version)",
     "legendFormat": "{{job_name}} {{job_version}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Up",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "avg(up{job_name=~\"$job_name\",job_version=~\"$job_version\"}) by (job_name, job_version)",
     "legendFormat": "{{job_name}} {{job_version}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - avg(process_start_time_seconds{job_name=~\"$job_name\",job_version=~\"$job_version\"}) by (job_name, job_version))",
     "legendFormat": "{{job_name}} {{job_version}}"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 32 },
   "targets": [
    {
     "expr": "sum(process_open_fds{job_name=~\"$job_name\",job_version=~\"$job_version\"})",
     "legendFormat": "open file descriptors"
    },
    {
     "expr": "sum(rate(python_gc_collections_total{job_name=~\"$job_name\",job_version=~\"$job_version\"}[$__rate_interval]))",
     "legendFormat": "GC collections rate"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Virtual memory (approximate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job_name=~\"$job_name\",job_version=~\"$job_version\"}",
     "legendFormat": "{{job_name}} {{job_version}}"
    }
   ]
  },
  {
   "title": "CPU usage (approximate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job_name=~\"$job_name\",job_version=~\"$job_version\"}[$__rate_interval])",
     "legendFormat": "{{job_name}} {{job_version}}"
    }
   ]
  }
 ]
}