{
 "title": "Lifecycle",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Deployments",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(requested_job_deployments_total[$__rate_interval]) > 0)",
     "legendFormat": "growth: requested deployments"
    },
    {
     "expr": "sum(requested_job_deployments_total)",
     "legendFormat": "total: requested deployments"
    },
    { "expr": "sum(deployed_job_total)", "legendFormat": "total: successful deployments" },
    {
     "expr": "sum(idelta(deployed_job_total[$__rate_interval]) > 0)",
     "legendFormat": "growth: successful deployments"
    }
   ]
  },
  {
   "title": "Database connection",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "lifecycle_database_connected", "legendFormat": "is_connected {{instance}}" }
   ]
  },
  {
   "title": "Jobs by status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jobs_count_by_status", "legendFormat": "{{status}}" }
   ]
  }
 ]
}