{
 "title": "Postgres",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Up",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pg_up" }
   ]
  },
  {
   "title": "Rows",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_database_tup_deleted)",
     "legendFormat": "rows deleted"
    },
    {
     "expr": "sum(pg_stat_database_tup_fetched)",
     "legendFormat": "rows fetched"
    },
    {
     "expr": "sum(pg_stat_database_tup_inserted)",
     "legendFormat": "rows inserted"
    },
    {
     "expr": "sum(pg_stat_database_tup_returned)",
     "legendFormat": "rows returned"
    },
    {
     "expr": "sum(pg_stat_database_tup_updated)",
     "legendFormat": "rows updated"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "pg_stat_activity_count",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count) by (state)"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_database_xact_commit) by (datname)",
     "legendFormat": "transactions commited {{datname}}"
    },
    {
     "expr": "sum(pg_stat_database_xact_rollback) by (datname)",
     "legendFormat": "transaction rollbacks {{datname}}"
    }
   ]
  },
  {
   "title": "Settings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pg_settings_max_connections", "legendFormat": "pg_settings_max_connections" }
   ]
  }
 ]
}