{
 "title": "PUB",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "filters" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(pub_job_proxy_requests, job_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Proxy requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of Job Proxy calls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(pub_job_proxy_requests{job_name=~\"$job_name\"}[$__rate_interval])) by (job_name, job_version)",
     "legendFormat": "{{job_name}} {{job_version}}"
    }
   ]
  },
  {
   "title": "Active requests (Unfinished)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(pub_job_proxy_requests_started{job_name=~\"$job_name\"} - pub_job_proxy_requests_done{job_name=~\"$job_name\"}) by (job_name, job_version)",
     "legendFormat": "{{job_name}} {{job_version}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(pub_job_proxy_errors[$__rate_interval]))",
     "legendFormat": "reverse proxy errors"
    },
    {
     "expr": "sum(irate(pub_job_proxy_request_errors[$__rate_interval]))",
     "legendFormat": "proxy request errors"
    }
   ]
  },
  {
   "title": "Proxy response time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Response time histogram over time",
   "type": "heatmap",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(idelta(pub_job_call_response_time_histogram_bucket{job_name=~\"$job_name\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response time histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (max_over_time(pub_job_call_response_time_histogram_bucket{job_name=~\"$job_name\"}[$__range])) - \nsum by(le) (min_over_time(pub_job_call_response_time_histogram_bucket{job_name=~\"$job_name\"}[$__range]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Average Job Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(pub_job_call_response_time{job_name=~\"$job_name\"}) by (job_name, job_version)) / (sum(pub_job_proxy_requests_done{job_name=~\"$job_name\"}) by (job_name, job_version))",
     "legendFormat": "{{job_name}} {{job_version}}"
    }
   ]
  },
  {
   "title": "Proxy response code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Response codes rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(pub_job_proxy_response_codes{status_code=\"200\",job_name=~\"$job_name\"}[$__rate_interval])) by (status_code, job_name, job_version)",
     "legendFormat": "{{status_code}} - {{job_name}} {{job_version}}"
    },
    {
     "expr": "sum(irate(pub_job_proxy_response_codes{status_code!=\"200\",job_name=~\"$job_name\"}[$__rate_interval])) by (status_code, job_name, job_version)",
     "legendFormat": "{{status_code}} - {{job_name}} {{job_version}}"
    }
   ]
  },
  {
   "title": "Total response codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sum(pub_job_proxy_response_codes{job_name=~\"$job_name\"}) by (status_code, job_name, job_version)",
     "legendFormat": "{{status_code}} - {{job_name}} {{job_version}}"
    }
   ]
  },
  {
   "title": "PUB internals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Internal PUB requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(pub_health_requests[$__rate_interval]))",
     "legendFormat": "health-check rate"
    },
    {
     "expr": "sum(irate(pub_lifecycle_calls[$__rate_interval]))",
     "legendFormat": "lifecycle calls rate"
    },
    {
     "expr": "sum(irate(pub_job_proxy_requests[$__rate_interval]))",
     "legendFormat": "total job proxy rate"
    }
   ]
  },
  {
   "title": "Lifecycle vs Job average response time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(pub_overall_job_proxy_response_time[$__rate_interval])) / sum(increase(pub_job_proxy_requests[$__rate_interval]))",
     "legendFormat": "overall Job proxy"
    },
    {
     "expr": "sum(increase(pub_lifecycle_call_time[$__rate_interval])) / sum(increase(pub_job_proxy_requests[$__rate_interval]))",
     "legendFormat": "lifecycle calls"
    },
    {
     "expr": "sum(increase(pub_job_call_response_time[$__rate_interval])) / sum(increase(pub_job_proxy_requests[$__rate_interval]))",
     "legendFormat": "job call"
    }
   ]
  },
  {
   "title": "Auth attempts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(pub_auth_failed[$__rate_interval]))",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(irate(pub_auth_successful[$__rate_interval]))",
     "legendFormat": "successful"
    }
   ]
  },
  {
   "title": "Go Misc",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"pub\"}",
     "legendFormat": "number of goroutines ({{instance}})"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"pub\"}",
     "legendFormat": "Memory allocated ({{instance}})"
    },
    {
     "expr": "sum(rate(promhttp_metric_handler_requests_total{job=\"pub\"}[$__rate_interval]))",
     "legendFormat": "Metrics scrapes rate"
    }
   ]
  }
 ]
}