infrastructure_targets:
  remote-k8s:
    remote_gateway_url: 'http://${public_ip}:7105/pub'
    remote_gateway_token: '${remote_gateway_token}'
    job_k8s_namespace: '${kubernetes_namespace}'

jobtype_extra:
  docker_registry: '${registry_hostname}'
  username: '${registry_username}'
  password: '${write_registry_token}'
