site_name: Racetrack
repo_name: TheRacetrack/racetrack
repo_url: https://github.com/TheRacetrack/racetrack
site_author: TheRacetrack
docs_dir: .
edit_uri: ''
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    logo: material/car-sports
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.expand
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - toc:
      permalink: true
plugins:
  - search
  - same-dir
  - exclude:
      glob:
        - venv/*
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TheRacetrack/racetrack
      name: Racetrack on GitHub

nav:
  - Introduction: README.md
  - Using Racetrack:
    - Quickstart: docs/quickstart.md
    - User Guide: docs/user.md
    - Job Manifest File Schema: docs/manifest-schema.md
    - Permission model: docs/permissions.md
    - CLI client: racetrack_client/README.md
  - Plugins:
    - Using plugins: docs/development/using-plugins.md
    - Developing plugins: docs/development/developing-plugins.md
    - Job type plugins: docs/development/plugins-job-types.md
  - Development:
    - Developer manual: docs/development/develop.md
    - Deployment & Release: docs/development/deployment.md
    - Bill of Materials: docs/development/bom.md
  - Administering: docs/admin.md
  - Changelog: docs/CHANGELOG.md
  - Glossary: docs/glossary.md
