site_name: Racetrack
repo_name: TheRacetrack/racetrack
repo_url: https://github.com/TheRacetrack/racetrack
site_author: TheRacetrack
docs_dir: .
edit_uri: ''
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  logo: docs/assets/logo/racetrack-logo-white.png
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.expand
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - toc:
      permalink: true
plugins:
  - search
  - same-dir
  - exclude:
      glob:
        - venv/*
        - dashboard/*
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TheRacetrack/racetrack
      name: Racetrack on GitHub

nav:
  - Introduction: README.md
  - Using Racetrack:
    - Quickstart: docs/quickstart.md
    - User Guide:
      - part 1 - Introduction: docs/user/user-guide-1.md
      - part 2 - Creating a Job: docs/user/user-guide-2.md
    - Available plugins: docs/user/available-plugins.md
    - Installing plugins: docs/user/using-plugins.md
    - Reference:
      - Job Manifest File Schema: docs/manifest-schema.md
      - CLI client: racetrack_client/README.md
      - Changelog: docs/CHANGELOG.md
    - Explanation:
      - Permission model: docs/permissions.md
      - Glossary: docs/glossary.md
  - Installation:
    - How-to guides:
      - Local Kubernetes Setup: docs/deployment/local-kubernetes-setup.md
      - Installation to standalone host: docs/deployment/standalone-host.md
      - Installation to non-local Kubernetes: docs/deployment/k8s-installation.md
      - Remote Kubernetes Gateway: docs/deployment/remote-kubernetes-gateway.md
      - Remote Docker Gateway: docs/deployment/remote-docker-gateway.md
    - Administering: docs/admin.md
  - Development:
    - Plugins:
      - Developing plugins: docs/development/developing-plugins.md
      - Job type plugins: docs/development/plugins-job-types.md
    - Developer manual: docs/development/develop.md
    - Releasing a version: docs/development/release.md
    - Bill of Materials: docs/development/bom.md
    - Copyright Notices: docs/license/copyright-notices.md
