# Generated by Django 3.2.3 on 2021-08-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='allowed_jobs',
            field=models.ManyToManyField(blank=True, to='registry.Job'),
        ),
        migrations.AlterField(
            model_name='esc',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='allowed_escs', to='registry.Job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('running', 'running'), ('error', 'error'), ('orphaned', 'orphaned'), ('lost', 'lost')], max_length=32),
        ),
    ]
