# Generated by Django 3.2.6 on 2021-08-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('registry', '0002_auto_20210809_1242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Job',
        ),
        migrations.RenameField(
            model_name='deployment',
            old_name='job_name',
            new_name='job_name',
        ),
        migrations.RenameField(
            model_name='esc',
            old_name='jobs',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='allowed_jobs',
            new_name='allowed_jobs',
        ),
    ]
