# Generated by Django 3.2.3 on 2021-08-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_rename_job_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image_tag',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
