# Generated by Django 3.2.6 on 2021-09-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_job_image_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='deployed_by',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='deployed_by',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
