# Generated by Django 3.2.6 on 2021-09-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_auto_20210902_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='esc',
            name='api_key',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='esc',
            name='caller_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
