# Generated by Django 3.2.6 on 2021-09-21 16:58

from django.db import migrations, models
import lifecycle.django.registry.models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_auto_20210907_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esc',
            old_name='job',
            new_name='jobs',
        ),
        migrations.AlterField(
            model_name='esc',
            name='id',
            field=models.CharField(default=lifecycle.django.registry.models.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
