# Generated by Django 3.2.6 on 2021-10-07 16:58

from django.db import migrations, models
import django.db.models.deletion


def initialize_fatman_families(apps, schema_editor):
    Fatman = apps.get_model('registry', 'Fatman')
    FatmanFamily = apps.get_model('registry', 'FatmanFamily')

    for fatman in Fatman.objects.all():
        fatman.family = create_fatman_family_if_not_exist(fatman.name, FatmanFamily)
        if not fatman.version:
            fatman.version = '0.0.1'
        fatman.save()


def create_fatman_family_if_not_exist(fatman_name: str, FatmanFamily):
    try:
        return FatmanFamily.objects.get(name=fatman_name)
    except FatmanFamily.DoesNotExist:
        new_model = FatmanFamily(
            name=fatman_name,
        )
        new_model.save()
        return new_model


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_auto_20211007_1656'),
    ]

    operations = [
        migrations.RunPython(initialize_fatman_families),
        # disallow null family
        migrations.AlterField(
            model_name='fatman',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.fatmanfamily'),
        ),
    ]
