# Generated by Django 3.2.6 on 2021-10-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0011_alter_job_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='build_logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
