# Generated by Django 3.2.6 on 2021-11-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_jobfamily_api_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esc',
            old_name='caller_token',
            new_name='esc_auth',
        ),
    ]
