# Generated by Django 3.2.6 on 2021-11-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0014_rename_caller_token_esc_esc_auth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esc',
            options={'verbose_name': 'External service consumer', 'verbose_name_plural': 'External service consumers'},
        ),
        migrations.AlterModelOptions(
            name='fatman',
            options={'verbose_name_plural': 'Fatmen'},
        ),
        migrations.AlterModelOptions(
            name='fatmanfamily',
            options={'verbose_name_plural': 'Fatman families'},
        ),
    ]
