# Generated by Django 3.2.6 on 2021-11-23 19:07

from django.db import migrations, models
import django.db.models.deletion
import lifecycle.django.registry.models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0015_auto_20211117_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicEndpointRequest',
            fields=[
                ('id', models.CharField(default=lifecycle.django.registry.models.new_uuid, max_length=36, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=512)),
                ('active', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.job')),
            ],
            options={
                'verbose_name_plural': 'Public endpoint requests',
            },
        ),
    ]
