# Generated by Django 3.2.6 on 2022-01-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0016_publicendpointrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='phase',
            field=models.TextField(blank=True, null=True),
        ),
    ]
