# Generated by Django 3.2.6 on 2022-03-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_deployment_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_call_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
