# Generated by Django 3.2.6 on 2022-05-04 12:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registry', '0021_migrate_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esc',
            name='allowed_job_families',
        ),
        migrations.RemoveField(
            model_name='esc',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='esc',
            name='esc_auth',
        ),
        migrations.RemoveField(
            model_name='jobfamily',
            name='allowed_job_families',
        ),
        migrations.RemoveField(
            model_name='jobfamily',
            name='api_key',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
