# Generated by Django 3.2.13 on 2022-06-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0023_default_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='image_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
