# Generated by Django 3.2.13 on 2022-08-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0024_deployment_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authresourcepermission',
            name='all_resources',
        ),
        migrations.AddField(
            model_name='authresourcepermission',
            name='endpoint',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
