# Generated by Django 3.2.16 on 2023-02-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0027_rename_fatman_to_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fatman',
            new_name='Job',
        ),
        migrations.RenameModel(
            old_name='FatmanFamily',
            new_name='JobFamily',
        ),
        migrations.RenameModel(
            old_name='TrashFatman',
            new_name='TrashJob',
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='jobfamily',
            options={'verbose_name_plural': 'Job families'},
        ),
        migrations.AlterModelOptions(
            name='trashjob',
            options={'verbose_name_plural': 'Trash Jobs'},
        ),
        migrations.RenameField(
            model_name='auditlogevent',
            old_name='fatman_name',
            new_name='job_name',
        ),
        migrations.RenameField(
            model_name='auditlogevent',
            old_name='fatman_version',
            new_name='job_version',
        ),
        migrations.RenameField(
            model_name='authresourcepermission',
            old_name='fatman',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='authresourcepermission',
            old_name='fatman_family',
            new_name='job_family',
        ),
        migrations.RenameField(
            model_name='authsubject',
            old_name='fatman_family',
            new_name='job_family',
        ),
        migrations.RenameField(
            model_name='deployment',
            old_name='fatman_name',
            new_name='job_name',
        ),
        migrations.RenameField(
            model_name='deployment',
            old_name='fatman_version',
            new_name='job_version',
        ),
        migrations.RenameField(
            model_name='publicendpointrequest',
            old_name='fatman',
            new_name='job',
        ),
    ]
