# Generated by Django 4.1.7 on 2023-03-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0029_job_replica_internal_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_type_version",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
