# Generated by Django 4.1.9 on 2023-06-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0030_job_job_type_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="notice",
            field=models.TextField(blank=True, null=True),
        ),
    ]
