# Generated by Django 4.1.10 on 2023-11-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0031_job_notice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "name",
                    models.CharField(max_length=512, primary_key=True, serialize=False),
                ),
                ("value", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Settings",
            },
        ),
    ]
