# Generated by Django 4.1.10 on 2024-01-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0032_setting"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlogevent",
            index=models.Index(fields=["timestamp"], name="timestamp_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlogevent",
            index=models.Index(
                fields=["username_executor"], name="username_executor_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlogevent",
            index=models.Index(fields=["job_name"], name="job_name_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlogevent",
            index=models.Index(fields=["job_version"], name="job_version_idx"),
        ),
        migrations.AddIndex(
            model_name="deployment",
            index=models.Index(fields=["update_time"], name="update_time_idx"),
        ),
    ]
