# Generated by Django 4.2.7 on 2024-03-11 16:11

from django.db import migrations, models
import lifecycle.django.registry.models
import racetrack_client.utils.time


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0033_auditlogevent_timestamp_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsyncJobCall",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=lifecycle.django.registry.models.new_uuid,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ongoing", "ongoing"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(default=racetrack_client.utils.time.now),
                ),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("job_name", models.CharField(max_length=512)),
                ("job_version", models.CharField(max_length=256)),
                ("job_path", models.CharField(blank=True, max_length=512)),
                ("request_method", models.CharField(max_length=32)),
                ("request_url", models.CharField(max_length=512)),
                ("request_headers", models.JSONField(blank=True, null=True)),
                ("request_body", models.BinaryField(blank=True)),
                ("response_status_code", models.IntegerField(null=True)),
                ("response_headers", models.JSONField(blank=True, null=True)),
                ("response_body", models.BinaryField(blank=True)),
                ("attempts", models.IntegerField(default=0)),
                ("pub_instance_addr", models.CharField(blank=True, max_length=256)),
            ],
            options={
                "verbose_name_plural": "Async Job Calls",
            },
        ),
    ]
