# Generated by Django 4.2.7 on 2024-04-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0034_asyncjobcall"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("starting", "starting"),
                    ("running", "running"),
                    ("error", "error"),
                    ("orphaned", "orphaned"),
                    ("lost", "lost"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="trashjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("starting", "starting"),
                    ("running", "running"),
                    ("error", "error"),
                    ("orphaned", "orphaned"),
                    ("lost", "lost"),
                ],
                max_length=32,
            ),
        ),
    ]
