# Generated by Django 4.2.7 on 2024-05-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0035_alter_job_status_alter_trashjob_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="infrastructure_stats",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
