# Generated by Django 4.2.7 on 2024-07-24 08:47

from django.db import migrations, models
import django.db.models.deletion
import lifecycle.django.registry.models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0037_deployment_warnings"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthToken",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=lifecycle.django.registry.models.new_uuid,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=1024)),
                ("expiry_time", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("last_use_time", models.DateTimeField(blank=True, null=True)),
                (
                    "auth_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registry.authsubject",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["token"], name="token_idx")],
            },
        ),
    ]
