# Generated by Django 4.2.7 on 2024-07-18 13:27

from django.db import migrations, models
import django.db.models.deletion
import lifecycle.django.registry.models


def move_tokens_to_auth_token_models(apps, schema_editor):
    AuthSubject = apps.get_model('registry', 'AuthSubject')
    AuthToken = apps.get_model('registry', 'AuthToken')
    for auth_subject in AuthSubject.objects.all():
        auth_token = AuthToken()
        auth_token.auth_subject = auth_subject
        auth_token.token = auth_subject.token
        auth_token.expiry_time = auth_subject.expiry_time
        auth_token.active = auth_subject.active
        auth_token.save()


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0037_deployment_warnings"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthToken",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=lifecycle.django.registry.models.new_uuid,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=1024)),
                ("expiry_time", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "auth_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registry.authsubject",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["token"], name="token_idx")],
            },
        ),
        migrations.RunPython(move_tokens_to_auth_token_models),
        migrations.RemoveField(
            model_name="authsubject",
            name="active",
        ),
        migrations.RemoveField(
            model_name="authsubject",
            name="expiry_time",
        ),
        migrations.RemoveField(
            model_name="authsubject",
            name="token",
        ),
    ]
