infrastructure_targets:
  remote-docker-daemon:
    remote_gateway_url: 'http://${public_ip}:7105/pub'
    remote_gateway_token: '${remote_gateway_token}'

jobtype_extra:
  docker_registry: '${registry_hostname}'
  username: '${registry_username}'
  password: '${write_registry_token}'
