apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: racetrack
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
    spec:
      securityContext:
        fsGroup: 100000
        runAsUser: 100000
        runAsGroup: 100000
      serviceAccountName: null
      priorityClassName: high-priority
      containers:
        - name: grafana
          image: grafana/grafana:9.3.6
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          tty: true

---
apiVersion: v1
kind: Service
metadata:
  namespace: racetrack
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
spec:
  selector:
    app.kubernetes.io/name: grafana
  type: NodePort
  ports:
    - name: grafana
      nodePort: 30300
      port: 3000
      targetPort: 3000
