apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: racetrack
  name: pub
  labels:
    app.kubernetes.io/name: pub
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pub
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pub
    spec:
      hostname: pub
      subdomain: pub
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/name"
                      operator: In
                      values:
                        - pub
                topologyKey: kubernetes.io/hostname
      priorityClassName: high-priority
      containers:
        - name: pub
          image: racetrack-registry:5000/racetrack/pub:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7005
          tty: true
          env:
            - name: PUB_PORT
              value: '7005'
            - name: LIFECYCLE_URL
              value: 'http://lifecycle:7002/lifecycle'
            - name: AUTH_REQUIRED
              value: 'true'
            - name: AUTH_DEBUG
              value: 'true'
            - name: LIFECYCLE_AUTH_TOKEN
              value: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZWVkIjoiY2E3ZWNmODAtZDAxZS00ZjA5LWI4ZjQtMTZiNTMxYjhhOTNhIiwic3ViamVjdCI6InB1YiIsInN1YmplY3RfdHlwZSI6ImludGVybmFsIiwic2NvcGVzIjpbImZ1bGxfYWNjZXNzIl19.Xyg1lwQG4oiA65y-KAkdmCFjnT7BZkfmm66DDGOVZu4'
            - name: REPLICA_DISCOVERY_HOSTNAME
              value: 'pub.pub.racetrack.svc.cluster.local'
          livenessProbe:
            httpGet:
              path: /live
              port: 7005
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 7005
            initialDelaySeconds: 3
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  namespace: racetrack
  name: pub
  labels:
    app.kubernetes.io/name: pub
spec:
  selector:
    app.kubernetes.io/name: pub
  type: NodePort
  ports:
    - name: pub
      nodePort: 30005
      port: 7005
      targetPort: 7005
