name: gh-pages
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install documentation tools
        run: pip install -r requirements-dev.txt

      - name: Deploy mkdocs to Github Pages
        run: make mkdocs-push
