log_level: debug
http_port: 7002
infrastructure_target: kubernetes
image_builder_url: http://image-builder:7001
internal_pub_url: http://pub:7005/pub
external_pub_url: http://1.1.1.1/pub
docker_registry:
docker_registry_namespace:
auth_required: true
auth_debug: true
plugins_dir: /mnt/plugins
